# Prometheus configuration for Baserow monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Baserow application metrics
  - job_name: 'baserow'
    static_configs:
      - targets: ['baserow:8000']
    metrics_path: '/api/_health/'
    scrape_interval: 30s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # MCP server metrics
  - job_name: 'baserow-mcp'
    static_configs:
      - targets: ['baserow:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Uptime monitoring
  - job_name: 'uptime-kuma'
    static_configs:
      - targets: ['uptime-kuma:3001']
    scrape_interval: 60s

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
